const router = require('express').Router();
const { PrismaClient } = require('@prisma/client');
const { auth } = require('../middleware/auth');
const { recalculateBudget } = require('../utils/budgetCalculator');
const PDFDocument = require('pdfkit');
const prisma = new PrismaClient();

router.get('/:tripId', auth, async (req, res) => {
  try {
    const trip = await prisma.trip.findFirst({
      where: { id: req.params.tripId, userId: req.userId },
      include: {
        user: { select: { firstName: true, lastName: true, email: true } },
        stops: { include: { activities: true } },
        expenses: { orderBy: { date: 'asc' } }
      }
    });
    if (!trip) return res.status(404).json({ error: 'Trip not found' });
    const budget = await recalculateBudget(req.params.tripId, prisma);
    res.json({ trip, budget });
  } catch (error) { res.status(500).json({ error: error.message }); }
});

router.get('/:tripId/pdf', auth, async (req, res) => {
  try {
    const trip = await prisma.trip.findFirst({
      where: { id: req.params.tripId, userId: req.userId },
      include: {
        user: { select: { firstName: true, lastName: true } },
        stops: { include: { activities: true } },
        expenses: { orderBy: { category: 'asc' } }
      }
    });
    if (!trip) return res.status(404).json({ error: 'Trip not found' });
    const budget = await recalculateBudget(req.params.tripId, prisma);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=traveloop-${trip.name.replace(/\s+/g, '-')}.pdf`);
    doc.pipe(res);

    doc.fontSize(24).fillColor('#1D9E75').text('TRAVELOOP', { align: 'center' });
    doc.fontSize(12).fillColor('#666').text('Trip Expense Invoice', { align: 'center' });
    doc.moveDown().moveTo(50, doc.y).lineTo(545, doc.y).stroke('#1D9E75').moveDown();

    doc.fontSize(16).fillColor('#333').text(trip.name);
    doc.fontSize(11).fillColor('#666')
      .text(`Traveler: ${trip.user.firstName} ${trip.user.lastName}`)
      .text(`Travel Dates: ${trip.startDate.toDateString()} — ${trip.endDate.toDateString()}`)
      .text(`Destinations: ${trip.stops.map(s => s.city).join(', ') || 'N/A'}`);
    doc.moveDown();

    doc.fontSize(13).fillColor('#1D9E75').text('Budget Summary');
    doc.fontSize(11).fillColor('#333')
      .text(`Total Budget: $${budget.totalBudget.toFixed(2)}`)
      .text(`Total Spent: $${budget.totalSpent.toFixed(2)}`)
      .text(`Remaining: $${budget.remaining.toFixed(2)}`)
      .text(`Status: ${budget.status.toUpperCase()}`);
    doc.moveDown();

    if (trip.expenses.length > 0) {
      doc.fontSize(13).fillColor('#1D9E75').text('Expense Details');
      doc.moveDown(0.5);
      const headers = ['#', 'Category', 'Description', 'Amount'];
      const colW = [30, 100, 260, 80];
      let x = 50;
      doc.fontSize(10).fillColor('#fff');
      doc.rect(50, doc.y, 480, 20).fill('#1D9E75');
      let headerY = doc.y - 15;
      headers.forEach((h, i) => { doc.fillColor('#fff').text(h, x + 4, headerY); x += colW[i]; });
      doc.moveDown(0.5);

      trip.expenses.forEach((exp, idx) => {
        let rowX = 50;
        const rowY = doc.y;
        if (idx % 2 === 0) doc.rect(50, rowY - 2, 480, 16).fill('#f5f5f5');
        doc.fillColor('#333').fontSize(9);
        doc.text(String(idx + 1), rowX + 4, rowY); rowX += colW[0];
        doc.text(exp.category, rowX + 4, rowY); rowX += colW[1];
        doc.text(exp.description.substring(0, 40), rowX + 4, rowY); rowX += colW[2];
        doc.text(`$${exp.amount.toFixed(2)}`, rowX + 4, rowY);
        doc.moveDown(0.4);
      });
    }

    doc.moveDown();
    doc.fontSize(13).fillColor('#1D9E75').text('Breakdown by Category');
    Object.entries(budget.breakdown).forEach(([cat, amount]) => {
      if (amount > 0) doc.fontSize(11).fillColor('#333').text(`${cat.charAt(0).toUpperCase() + cat.slice(1)}: $${amount.toFixed(2)}`);
    });

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#999').text('Generated by Traveloop — Personalized Travel Planning Made Easy', { align: 'center' });
    doc.end();
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
