import api from './client';

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export const tripsAPI = {
  getAll: (params) => api.get('/trips', { params }),
  getOne: (id) => api.get(`/trips/${id}`),
  create: (data) => api.post('/trips', data),
  update: (id, data) => api.put(`/trips/${id}`, data),
  delete: (id) => api.delete(`/trips/${id}`),
  addStop: (data) => api.post('/stops', data),
  updateStop: (id, data) => api.put(`/stops/${id}`, data),
  deleteStop: (id) => api.delete(`/stops/${id}`),
  addActivity: (data) => api.post('/activities', data),
  deleteActivity: (id) => api.delete(`/activities/${id}`),
  getBudget: (tripId) => api.get(`/budget/${tripId}`),
  getExpenses: (tripId) => api.get(`/expenses/${tripId}`),
  addExpense: (data) => api.post('/expenses', data),
  deleteExpense: (id) => api.delete(`/expenses/${id}`),
  getPacking: (tripId) => api.get(`/packing/${tripId}`),
  addPackingItem: (data) => api.post('/packing', data),
  updatePackingItem: (id, data) => api.put(`/packing/${id}`, data),
  deletePackingItem: (id) => api.delete(`/packing/${id}`),
  resetPacking: (tripId) => api.post(`/packing/${tripId}/reset`),
  getNotes: (tripId, params) => api.get(`/notes/${tripId}`, { params }),
  addNote: (data) => api.post('/notes', data),
  updateNote: (id, data) => api.put(`/notes/${id}`, data),
  deleteNote: (id) => api.delete(`/notes/${id}`),
  getInvoice: (tripId) => api.get(`/invoice/${tripId}`),
  downloadPDF: (tripId) => window.open(`${BASE_URL}/invoice/${tripId}/pdf`, '_blank'),
  getCommunity: (params) => api.get('/community', { params }),
  shareTrip: (tripId, data) => api.post(`/community/share/${tripId}`, data),
  likePost: (postId) => api.post(`/community/like/${postId}`),
  cloneTrip: (tripId) => api.post(`/community/clone/${tripId}`),
  aiSuggest: (tripId) => api.post('/ai/suggest-itinerary', { tripId }),
  aiPacking: (tripId) => api.post('/ai/generate-packing', { tripId }),
  aiChat: (message, tripContext) => api.post('/ai/chat', { message, tripContext }),
  adminStats: () => api.get('/admin/stats'),
  adminUsers: () => api.get('/admin/users'),
  getPublicTrip: (id) => api.get(`/trips/public/${id}`),
  getTripSummary: (tripId) => api.post('/ai/trip-summary', { tripId }),
  searchCities: (params) => api.get('/cities', { params }),
  searchActivities: (params) => api.get('/activity-search', { params }),
};
